### ISSUE TITLE
Problem with output format

### ISSUE THREAD

**Issue by overthink** [YasithLokuge/sortable#1]
Hi Yasith,

I was trying to evaluate your solution but there is a problem with the output format. Please make sure each line in the output file is a Result object as described on http://sortable.com/challenge/, i.e.

```
{
  "product_name": String
  "listings": Array[Listing]
}

```

An example line in the output file should look like:

```
{"listings": [{"currency": "USD", "price": "189.00", "manufacturer": "CASIO", "title": "Casio EX-FC150 10.1MP High Speed Digital Camera with 5x Zoom with CMOS Shift Image Stabilization and 2.7 inch LCD (Red)"}, {"currency": "USD", "price": "189.00", "manufacturer": "CASIO", "title": "Casio Exilim EX-FC150 10.1MP High Speed Digital Camera with 5x Optical Zoom, CMOS Shift Image Stabilization & 2.7-inch LCD (Red)"}, {"currency": "USD", "price": "249.00", "manufacturer": "CASIO", "title": "Casio EX-FC150 10.1MP High Speed Digital Camera with 5x Zoom with CMOS Shift Image Stabilization and 2.7 inch LCD (Black)"}], "product_name": "Casio_Exilim_EX-FC150"}
```

In your case each value in the listings array seems to be double-quoted like a string.  These items should be objects.

You can validate your output format using the following:

`curl -XPOST -F file=@/path/to/your/results.txt https://challenge-check.sortable.com/validate`

If you are able to fix this up I'd be happy to take another look at your submission.

Thanks!

Mark (from sortable.com)

**Comment by Yasith-Lokuge** [comment]
Output file not getting validated properly, reopening the issue.

**Comment by overthink** [comment]
Looks like double quotes are not escaped inside listing titles?

**Comment by Yasith-Lokuge** [comment]
[0ae7ad3](https://github.com/YasithLokuge/sortable/commit/0ae7ad3d345cfdde895d248630d70dcb949dc088) commit fixed the issue. Please check.

**Comment by overthink** [comment]
Looks good now.  Thanks for the fix.
